version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - echo Entered the install phase...
      - npm install
    finally:
      - echo Install completed.
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run-script build
      - cd build
      - aws s3 sync . s3://alterscript.io --delete --acl public-read
    finally:
      - echo This build completed.
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - build/**/*
  discard-paths: yes
